name: Deploy to Google Cloud Platform

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - id: auth
              uses: 'google-github-actions/auth@v2'
              with:
                project_id: 'quant-ai-agent'
                workload_identity_provider: 'projects/127312197691/locations/global/workloadIdentityPools/github/providers/my-repo' # "projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo"
                service_account: 'github-actions-account@quant-ai-agent.iam.gserviceaccount.com'

            - id: deploy
              name: Deploy to App Engine
              uses: google-github-actions/deploy-appengine@v2.1.3
              with:
                  deliverables: app.yaml
                  promote: true

            - name: Test
              run: curl "${{ steps.deploy.outputs.url }}"
